name: Build Flutter APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0" # Replace with a valid stable version
          cache: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Check for Android embedding v2 compatibility
      - name: Verify Android embedding migration
        run: |
          if grep -q "io.flutter.app.FlutterApplication" android/app/src/main/AndroidManifest.xml; then
            echo "Error: The project is still using Android embedding v1. Please migrate to embedding v2.";
            exit 1;
          fi
          if grep -q "GeneratedPluginRegistrant" android/app/src/main/kotlin/**/*.kt; then
            echo "Error: The MainActivity is still using v1 methods. Ensure migration to embedding v2 is complete.";
            exit 1;
          fi

      # Step 5: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 6: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
