name: Build Flutter APK

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the "main" branch
  pull_request: # Optional: Run on pull requests as well
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable # Use the stable Flutter version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Build APK
    - name: Build APK
      run: flutter build apk --release

    # Step 5: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
